### ISSUE TITLE
Insurance

### ISSUE THREAD

**Issue by TurkNoodle** [darknessresides/LDGAltis#9]
For many poor/ cheap people like myself insurance on things like civ cars and helicopter's would help a lot.

Hope you look into implementing this in a manner shown bellow
_______________________________________________________________________________________________________________STEPS TO GETING INSURANCE
1.When you buy a vehicle you can buy Insurance to go along with the 
2.when your vehicle is destroyed or lost you can head to a place (DMV for example) to get it back for a fraction of the price
_______________________________________________________________________________________________________________
EXTRA 
- Insurance can be put on Helicopter's, Cars, Boats, Trucks, & Planes
_______________________________________________________________________________________________________________

INFO 

Steam- http://steamcommunity.com/id/ChaboeTurk/
TeamSpeak Name- TURK
In Game Name- Stunner

**Comment by darknessresides** [comment]
Looking into this if it's possible, which it seems to be so far. Will have a tiny vote on it to see if it's worthwhile to fully look in to.

**Comment by darknessresides** [comment]
Added to the server. It will show up when you are pulling vehicles OUT OF YOUR GARAGE via the menu only and it will tell you the state of insurance and the cost. As of right now, it's set at a decent price which will be revisited in the future just in case I set the multiplier too high.

Please note the vehicle will re-appear back in your garage only after it has exploded and disappeared fully from it's destroyed state,  meaning it's no longer there to be impounded, and then the insurance will kick in.
